-- Migration: 028_create_ht_sessions
-- Version: 2.60.0
-- Date: 2026-05-10
-- Description: Phase 4 PR1 — backend authentication foundation.
--              Creates the `ht_sessions` table holding active user sessions.
--              The HttpOnly cookie value IS the `session_id` PK (a 32-byte
--              random hex token); rows are deleted on logout and pruned
--              periodically by `expires_at`.
--
-- ## Why this exists
--
-- We chose an opaque server-side session over a JWT so revocation is
-- trivial (DELETE FROM ht_sessions WHERE session_id = $1) and so the
-- cookie carries no claims beyond the random token. The token itself is
-- the bearer credential — argon2-hashing it adds no real value when the
-- attacker who possesses the cookie already has a valid session.
--
-- ## Columns
--
--   session_id    VARCHAR(64)  PK            -- 32 random bytes hex-encoded
--                                            -- (= 64 chars). Generated by
--                                            -- `AuthService::login`.
--   user_id       BIGINT NOT NULL FK -> ht_users(user_id) ON DELETE CASCADE
--   created_at    TIMESTAMP NOT NULL DEFAULT NOW()
--   expires_at    TIMESTAMP NOT NULL          -- session lifetime upper bound
--                                            -- (PR1 default = NOW() + 24h)
--   ip            INET                         -- client IP at login (audit)
--   user_agent    TEXT                         -- browser UA at login (audit)
--
-- ## Indexes
--
-- - PK on `session_id` (auto).
-- - `ix_ht_sessions_expires_at` on `expires_at` so the periodic cleanup
--   job (`AuthService::delete_expired`) can scan + delete in one pass.
-- - No index on `user_id` for PR1 — login does not need to enumerate a
--   user's active sessions yet. PR2 admin UI may add one when it grows
--   "force logout all sessions for user X".

-- =============================================================================
-- UP MIGRATION
-- =============================================================================

CREATE TABLE IF NOT EXISTS ht_sessions (
    session_id  VARCHAR(64) PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES ht_users(user_id) ON DELETE CASCADE,
    created_at  TIMESTAMP   NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMP   NOT NULL,
    ip          INET,
    user_agent  TEXT
);

CREATE INDEX IF NOT EXISTS ix_ht_sessions_expires_at
    ON ht_sessions (expires_at);

-- Schema-migrations row is inserted by scripts/migrate.sh (same TX, includes
-- the file checksum). Do NOT INSERT here.

-- =============================================================================
-- DOWN MIGRATION (commented for reference)
-- =============================================================================
-- DROP INDEX IF EXISTS ix_ht_sessions_expires_at;
-- DROP TABLE IF EXISTS ht_sessions;
-- DELETE FROM schema_migrations WHERE version = '028';
