-- Migration: 051_create_ht_coupons
-- Version: vNext
-- Date: 2026-05-14
-- Track G5 — canonical coupon issuing. Mirrors iHOTEL's `HT_Cupon`
-- food/breakfast coupon-entitlement table so receptionists can issue
-- coupons from the new app without falling back to iHOTEL.
--
-- ## Background
--
-- `HT_Cupon` in legacy is a food/breakfast coupon entitlement table:
-- one row per (check-in × night × `Cin_cupon` count). Today only
-- iHOTEL's `Module1.GEN_Cupon` writes to it (called at check-in time
-- and on print). Per `docs/legacy-app/COMPAT_CHEATSHEET.md` §`HT_Cupon`
-- the schema is `cupon_no int (NOT IDENTITY), cupon_cin_no varchar(50),
-- cupon_cin_room varchar(50), cupon_date datetime, cupon_gen_date
-- datetime, cupon_by varchar(50), cupon_print int DEFAULT 0`.
--
-- We already mirror this table read-only via `legacy_mirror.ht_cupon`
-- (CT-hydrated by `sync::mappers::mirror::CuponMirrorMapper`). Track G5
-- promotes it to a canonical owned table so our app can ISSUE coupons
-- — closing the daily operational gap captured in T4 (audit
-- 2026-05-13) where receptionists were forced back into iHOTEL to
-- generate breakfast / loyalty coupons.
--
-- ## Columns
--
-- - `coupon_id BIGSERIAL PK` — canonical row id.
-- - `legacy_cupon_no INTEGER` — back-pointer to `HT_Cupon.cupon_no`
--   (legacy MAX+1 allocator). NULL until the writeback worker
--   back-populates after a successful INSERT. Partial UNIQUE so the
--   coexistence layer can dedupe (legacy may also push its own rows
--   via CT for coupons iHOTEL issued).
-- - `coupon_code VARCHAR(20) UNIQUE` — human-readable code printed on
--   the coupon (e.g. `COUP-A1B2C3D4`). Generated by the service from a
--   shortened v4 UUID. Legacy iHOTEL has no equivalent (it prints the
--   numeric `cupon_no`); our code provides a friendlier hand-out.
-- - `coupon_value NUMERIC(10,2)` — face value in baht. Defaults to 0
--   for legacy-style "entitlement" coupons that have no monetary value;
--   non-zero for promo / discount vouchers. Stored canonically; not
--   written to legacy (no equivalent column on `HT_Cupon`).
-- - `coupon_status VARCHAR(20)` — `issued` / `redeemed` / `expired` /
--   `cancelled`. Maps to legacy `cupon_print int` via the service's
--   `legacy_status_to_pg` helper: `0` ⇒ `issued`, `1` ⇒ `redeemed`.
-- - `coupon_issued_at TIMESTAMPTZ` — when our app minted the row.
--   Lands in legacy `cupon_gen_date`.
-- - `coupon_expires_at DATE NULL` — optional expiry. Canonical-only;
--   `HT_Cupon` has no expiry column.
-- - `coupon_issued_by TEXT` — operator username from auth context.
--   Mirrors legacy `cupon_by`.
-- - `coupon_for_cin_no VARCHAR(50)` — legacy `Cin_no` the coupon is
--   attached to (mirrors legacy `cupon_cin_no`). NULL for stand-alone
--   promo coupons not tied to any specific stay.
-- - `coupon_for_cust_id BIGINT REFERENCES ht_customers(cust_id) ON
--   DELETE SET NULL` — optional canonical customer link. Canonical-only;
--   `HT_Cupon` references the stay via `cupon_cin_no`, not a customer id.
-- - `coupon_redeemed_at TIMESTAMPTZ NULL` — when the coupon was printed
--   / redeemed. Mirrors the moment iHOTEL flips `cupon_print` to 1.
-- - `coupon_redeemed_cin_id BIGINT REFERENCES ht_checkins(cin_id) ON
--   DELETE SET NULL` — the canonical check-in this redemption was
--   applied against. Canonical-only.
-- - `aggregate_id UUID UNIQUE NOT NULL` — deterministic v5 UUID for
--   outbox / event-bus contracts (per `service::ids` convention).
-- - `source VARCHAR(20) NOT NULL DEFAULT 'canonical'` — origin label:
--   `canonical` for rows our app issued, `legacy` for rows hydrated
--   from `HT_Cupon` CT events via the upcoming `CouponMapper`.
-- - `created_at` / `updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()` —
--   audit timestamps following the project convention.
--
-- ## Indexes
--
-- - Partial UNIQUE on `legacy_cupon_no` (WHERE NOT NULL) — same shape
--   as Track G4 / migration 045 `rc_legacy_id`.
-- - Plain index on `coupon_status` for the "list outstanding coupons"
--   read path.
-- - Plain index on `coupon_for_cust_id` for the "customer's coupon
--   history" read path.
-- - Plain index on `coupon_for_cin_no` for joining with
--   `legacy_mirror.ht_cupon` during reconcile.

-- =============================================================================
-- UP MIGRATION
-- =============================================================================

CREATE TABLE IF NOT EXISTS ht_coupons (
    coupon_id              BIGSERIAL    PRIMARY KEY,
    legacy_cupon_no        INTEGER,
    coupon_code            VARCHAR(20)  NOT NULL UNIQUE,
    coupon_value           NUMERIC(10,2) NOT NULL DEFAULT 0,
    coupon_status          VARCHAR(20)  NOT NULL DEFAULT 'issued',
    coupon_issued_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    coupon_expires_at      DATE,
    coupon_issued_by       TEXT,
    coupon_for_cin_no      VARCHAR(50),
    coupon_for_cust_id     BIGINT       REFERENCES ht_customers(cust_id) ON DELETE SET NULL,
    coupon_redeemed_at     TIMESTAMPTZ,
    coupon_redeemed_cin_id BIGINT       REFERENCES ht_checkins(cin_id)   ON DELETE SET NULL,
    aggregate_id           UUID         NOT NULL UNIQUE,
    source                 VARCHAR(20)  NOT NULL DEFAULT 'canonical',
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT ht_coupons_status_check
        CHECK (coupon_status IN ('issued', 'redeemed', 'expired', 'cancelled')),
    CONSTRAINT ht_coupons_source_check
        CHECK (source IN ('canonical', 'legacy')),
    CONSTRAINT ht_coupons_value_nonneg
        CHECK (coupon_value >= 0)
);

-- Partial UNIQUE on the legacy back-pointer (NULL during the window
-- between canonical INSERT and the writeback worker stamping the
-- legacy id; partial unique mirrors Track G4 / 045's rc_legacy_id).
CREATE UNIQUE INDEX IF NOT EXISTS ux_ht_coupons_legacy_cupon_no
    ON ht_coupons (legacy_cupon_no)
    WHERE legacy_cupon_no IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ht_coupons_status
    ON ht_coupons (coupon_status);

CREATE INDEX IF NOT EXISTS ix_ht_coupons_for_cust_id
    ON ht_coupons (coupon_for_cust_id)
    WHERE coupon_for_cust_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_ht_coupons_for_cin_no
    ON ht_coupons (coupon_for_cin_no)
    WHERE coupon_for_cin_no IS NOT NULL;

-- =============================================================================
-- Seed: extend Track G7 permission catalog with coupon.issue + coupon.redeem
-- =============================================================================
--
-- Mirrors the migration-046 grant grid: receptionist + admin can issue
-- and redeem coupons (matches iHOTEL where any logged-in user can use
-- FrmCuponMain). Cashier inherits redeem via the admin-covers-cashier
-- chain. Housekeeping is excluded — they don't handle the front desk
-- coupon workflow.

INSERT INTO ht_permissions (permission_key, description)
VALUES
    ('coupon.issue',  'Issue a food/promo coupon to a guest (Track G5)'),
    ('coupon.redeem', 'Mark a coupon as redeemed / printed (Track G5)')
ON CONFLICT (permission_key) DO NOTHING;

-- admin → both (covered by migration 046's "admin gets all" pattern,
-- but re-applied idempotently so a fresh install carries the grant).
INSERT INTO ht_role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM ht_roles r
CROSS JOIN ht_permissions p
WHERE r.role_key = 'admin'
  AND p.permission_key IN ('coupon.issue', 'coupon.redeem')
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- receptionist → both. Front-desk task; matches iHOTEL's permissive
-- gating on FrmCuponMain.
INSERT INTO ht_role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM ht_roles r
JOIN ht_permissions p ON p.permission_key IN ('coupon.issue', 'coupon.redeem')
WHERE r.role_key = 'receptionist'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- cashier → redeem only (cashiers may print/use coupons during
-- check-out billing; issuing is a receptionist task).
INSERT INTO ht_role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM ht_roles r
JOIN ht_permissions p ON p.permission_key = 'coupon.redeem'
WHERE r.role_key = 'cashier'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Schema-migrations row is inserted by scripts/migrate.sh (same TX,
-- includes the file checksum). Do NOT INSERT here.

-- =============================================================================
-- DOWN MIGRATION (commented for reference)
-- =============================================================================
-- DELETE FROM ht_role_permissions
--     WHERE permission_id IN (
--         SELECT permission_id FROM ht_permissions
--          WHERE permission_key IN ('coupon.issue', 'coupon.redeem')
--     );
-- DELETE FROM ht_permissions
--     WHERE permission_key IN ('coupon.issue', 'coupon.redeem');
-- DROP INDEX IF EXISTS ix_ht_coupons_for_cin_no;
-- DROP INDEX IF EXISTS ix_ht_coupons_for_cust_id;
-- DROP INDEX IF EXISTS ix_ht_coupons_status;
-- DROP INDEX IF EXISTS ux_ht_coupons_legacy_cupon_no;
-- DROP TABLE IF EXISTS ht_coupons;
-- DELETE FROM schema_migrations WHERE version = '051';
