-- Table: dbo.HT_Bank_AccountsCREATE TABLE [dbo].[HT_Bank_Accounts] (  [id] int,  [AC_NAME] varchar(100),  [AC_BANK_NAME] varchar(100),  [AC_BANK_NO] varchar(100),  [AC_BANK_TYPE] varchar(100),  [AC_BANK_BRANCH] varchar(100));
-- Table: dbo.HT_Bank_TransferCREATE TABLE [dbo].[HT_Bank_Transfer] (  [id] int,  [Bank_Name] varchar(100),  [Bank_Account_Name] varchar(100),  [Bank_Account_No] varchar(100),  [Bank_Account_Type] varchar(100),  [Bank_Account_BRANCH] varchar(100), 
-- Table: dbo.HT_Bill_Debt_DsCREATE TABLE [dbo].[HT_Bill_Debt_Ds] (  [id] int IDENTITY NOT NULL,  [Bill_No] varchar(20),  [DS_ID] int,  [DS_NO] varchar(50),  [DS_NAME] varchar(250),  [DS_UNIT] varchar(50),  [DS_NUM] float,  [DS_PRICE] float,  [DS
-- Table: dbo.HT_Bill_Debt_HCREATE TABLE [dbo].[HT_Bill_Debt_H] (  [Bill_No] varchar(20),  [Bill_Cust_ID] varchar(50),  [Bill_Cust_Name] varchar(250),  [Bill_Cust_Address] varchar(500),  [Bill_Cust_Tel] varchar(250),  [Bill_Cust_Fax] varchar(250), 
-- Table: dbo.HT_Book_DateCREATE TABLE [dbo].[HT_Book_Date] (  [id] int NOT NULL,  [Book_no] varchar(50),  [Book_type] varchar(50),  [Book_date_ds] datetime,  [Book_Num] int,  [Book_USE] int NOT NULL DEFAULT ((0)),  [Book_ok] int NOT NULL DEFAULT (
-- Table: dbo.HT_Book_DsCREATE TABLE [dbo].[HT_Book_Ds] (  [id] int IDENTITY NOT NULL,  [Book_No] varchar(50),  [Book_Room_Type] varchar(50),  [Book_Room_Start] datetime,  [Book_Room_End] datetime,  [Book_Room_Price] float,  [Book_Room_Night] float
-- Table: dbo.HT_Book_Ds2CREATE TABLE [dbo].[HT_Book_Ds2] (  [id] int,  [Book_No] varchar(50),  [Book_Room_Type] varchar(50),  [Book_Room_Ds] varchar(550),  [Book_Room_Num] float,  [Book_Room_Days] float,  [Book_Room_Price] float,  [Book_Room_Pric
-- Table: dbo.HT_Book_HCREATE TABLE [dbo].[HT_Book_H] (  [Book_ID] varchar(50),  [Book_Date] datetime,  [Book_Date_in] datetime,  [Book_Date_out] datetime,  [Book_Cust_ID] varchar(50),  [Book_Cust_Name] varchar(200),  [Book_Cust_Name2] varchar(200)
-- Table: dbo.HT_Book_H2CREATE TABLE [dbo].[HT_Book_H2] (  [id] int,  [Book_ID] varchar(50),  [Book_Date] datetime,  [Book_Date_in] datetime,  [Book_Date_out] datetime,  [Book_days] float,  [Book_Cust_ID] varchar(50),  [Book_Cust_Name] varchar(500
-- Table: dbo.HT_Book_ProCREATE TABLE [dbo].[HT_Book_Pro] (  [id] int IDENTITY NOT NULL,  [B_NO] varchar(50),  [B_ROOM] varchar(50),  [B_NAME] varchar(250),  [B_UNIT] varchar(50),  [B_NUM] float,  [B_PRICE] float,  [B_PRICE_TOTAL] float,  [B_PRO_
-- Table: dbo.HT_Book_StatusCREATE TABLE [dbo].[HT_Book_Status] (  [id] int,  [room_no] varchar(50),  [room_date] datetime,  [room_status] varchar(50),  [room_Details] varchar(500),  [room_Book_No] varchar(50),  [room_CheckIn_No] varchar(50));
-- Table: dbo.HT_Changed_RoomCREATE TABLE [dbo].[HT_Changed_Room] (  [id] int IDENTITY NOT NULL,  [cin_no] varchar(50) NOT NULL,  [room_before] varchar(50),  [room_after] varchar(50),  [change_date] datetime,  [room_before_price] float NOT NULL DEFA
-- Table: dbo.HT_CheckIn_DsCREATE TABLE [dbo].[HT_CheckIn_Ds] (  [id] int NOT NULL,  [Cin_No] varchar(50),  [Cin_Room_No] varchar(50),  [Cin_Room_Type] varchar(50),  [Cin_Room_In] datetime,  [Cin_Room_Out] datetime,  [Cin_Room_Status] varchar(500),
-- Table: dbo.HT_CheckIn_HCREATE TABLE [dbo].[HT_CheckIn_H] (  [Cin_no] varchar(50) NOT NULL,  [Cin_Date] datetime,  [Cin_Book_no] varchar(50),  [Cin_cust_no] varchar(50),  [Cin_cust_price] varchar(50),  [Cin_Car_type] varchar(50),  [Cin_Car_id] va
-- Table: dbo.HT_CheckIn_Other_PeopleCREATE TABLE [dbo].[HT_CheckIn_Other_People] (  [id] int IDENTITY NOT NULL,  [Cin_no] varchar(50),  [Cin_name] varchar(250),  [Cin_contry] varchar(50));
-- Table: dbo.HT_CheckIn_PayCREATE TABLE [dbo].[HT_CheckIn_Pay] (  [id] int IDENTITY NOT NULL,  [Pay_no] varchar(50),  [Cin_No] varchar(50),  [Cin_Pay_Ds] varchar(500),  [Cin_Pay_Cash] float,  [Cin_Pay_Credit] float,  [Cin_Pay_Date] datetime,  [Ci
-- Table: dbo.HT_CheckIn_ProductCREATE TABLE [dbo].[HT_CheckIn_Product] (  [id] int IDENTITY NOT NULL,  [Cin_No] varchar(50),  [Cin_Room_no] varchar(50),  [Cin_Ds_date] datetime,  [Cin_Pro_id] varchar(250),  [Cin_Pro_name] varchar(500),  [Cin_Pro_U
-- Table: dbo.HT_ContinueTimeCREATE TABLE [dbo].[HT_ContinueTime] (  [id] int IDENTITY NOT NULL,  [Con_Name] varchar(250),  [Con_Minute] int,  [Con_Price] float,  [Con_Type] varchar(50));
-- Table: dbo.HT_CuponCREATE TABLE [dbo].[HT_Cupon] (  [cupon_no] int,  [cupon_cin_no] varchar(50),  [cupon_cin_room] varchar(50),  [cupon_date] datetime,  [cupon_gen_date] datetime,  [cupon_by] varchar(50),  [cupon_print] int NOT NULL DEFAULT ((0)
-- Table: dbo.HT_CustomersCREATE TABLE [dbo].[HT_Customers] (  [id] int NOT NULL,  [Cust_no] varchar(50),  [Cust_perfix] varchar(50),  [Cust_name] varchar(250),  [Cust_name2] varchar(250),  [Cust_sex] varchar(50),  [Cust_IDcard] varchar(50),  [Cus
-- Table: dbo.HT_DepositCREATE TABLE [dbo].[HT_Deposit] (  [id] int,  [Dep_no] varchar(250),  [Dep_Date] datetime,  [Dep_Room] varchar(250),  [Dep_Name] varchar(250),  [Dep_Price] float,  [Dep_Status] varchar(50),  [Dep_ref] varchar(50));
-- Table: dbo.HT_EMP_SMSCREATE TABLE [dbo].[HT_EMP_SMS] (  [SMS_ID] int IDENTITY NOT NULL,  [SMS_TO] varchar(50),  [SMS_Details] text,  [SMS_By] varchar(250),  [SMS_Readed] varchar(50));
-- Table: dbo.HT_HousewifeCREATE TABLE [dbo].[HT_Housewife] (  [id] int IDENTITY NOT NULL,  [h_name] varchar(150),  [h_room] varchar(50),  [h_date] datetime,  [h_note] text,  [h_cin] varchar(50),  [h_cin_name] varchar(250));
-- Table: dbo.HT_INVOICECREATE TABLE [dbo].[HT_INVOICE] (  [INV_NO] int NOT NULL,  [INV_booking_no] varchar(50),  [INV_STAY] varchar(100),  [INV_DATE] datetime,  [INV_BY] varchar(50),  [INV_TITLE] varchar(400),  [INV_NAME] varchar(300),  [INV_COMP
-- Table: dbo.HT_Invoice_DsCREATE TABLE [dbo].[HT_Invoice_Ds] (  [id] int IDENTITY NOT NULL,  [S_Sale_id] int,  [S_Product_no] varchar(50),  [S_Product_name] varchar(50),  [S_Unit] float,  [S_UnitName] varchar(50),  [S_Price] float,  [S_Total] flo
-- Table: dbo.HT_Invoice_HCREATE TABLE [dbo].[HT_Invoice_H] (  [id] int,  [Receipt_no] varchar(50),  [Receipt_Date] datetime,  [Receipt_c_no] varchar(50),  [Receipt_Name] varchar(500),  [Receipt_Address] varchar(500),  [Receipt_Tel] varchar(50),  
-- Table: dbo.HT_Invoice_NoteCREATE TABLE [dbo].[HT_Invoice_Note] (  [Cin_no] varchar(50),  [note] text,  [NOTE_STATUS] varchar(20));
-- Table: dbo.HT_LogCREATE TABLE [dbo].[HT_Log] (  [id] int IDENTITY NOT NULL,  [details] varchar(250),  [Emp_name] varchar(150),  [DODATE] varchar(50));
-- Table: dbo.HT_Log_DebtCREATE TABLE [dbo].[HT_Log_Debt] (  [id] int IDENTITY NOT NULL,  [log_cus] varchar(50),  [log_ds] varchar(250),  [log_date] datetime,  [log_price_From] float,  [log_price] float,  [log_price_To] float);
-- Table: dbo.HT_Order_DownCREATE TABLE [dbo].[HT_Order_Down] (  [id] int,  [Cust_Type] varchar(50),  [Cust_Month] int,  [Cast_Type] varchar(250));
-- Table: dbo.HT_Order_UpCREATE TABLE [dbo].[HT_Order_Up] (  [id] int,  [Cust_Type] varchar(50),  [Cust_Month] int,  [Cast_Type] varchar(250));
-- Table: dbo.HT_POWER_LOGCREATE TABLE [dbo].[HT_POWER_LOG] (  [id] int IDENTITY NOT NULL,  [ROOM_NO] varchar(50),  [ROOM_POWER_START] datetime,  [ROOM_POWER_END] datetime,  [ROOM_POWER_START_BY] varchar(50),  [ROOM_POWER_END_BY] varchar(50),  [ROO
-- Table: dbo.HT_ProductsCREATE TABLE [dbo].[HT_Products] (  [id] int,  [Pro_no] varchar(50),  [Pro_Type] varchar(50),  [Pro_Name] varchar(500),  [Pro_PriceA] float,  [Pro_PriceB] float,  [Pro_PriceC] float,  [Pro_Amt] float,  [Pro_Unit] varchar(
-- Table: dbo.HT_Products_PriceCREATE TABLE [dbo].[HT_Products_Price] (  [id] int IDENTITY NOT NULL,  [P_ID] varchar(50),  [P_CustType] varchar(50),  [P_Price] float);
-- Table: dbo.HT_Receipt_DsCREATE TABLE [dbo].[HT_Receipt_Ds] (  [id] int IDENTITY NOT NULL,  [S_Sale_id] int,  [S_Product_no] varchar(50),  [S_Product_name] varchar(50),  [S_Unit] float,  [S_UnitName] varchar(50),  [S_Price] float,  [S_Total] flo
-- Table: dbo.HT_Receipt_HCREATE TABLE [dbo].[HT_Receipt_H] (  [id] int,  [Receipt_no] varchar(50),  [Receipt_Date] datetime,  [Receipt_c_no] varchar(50),  [Receipt_Name] varchar(500),  [Receipt_Address] varchar(500),  [Receipt_Tel] varchar(50),  
-- Table: dbo.HT_RegisterCREATE TABLE [dbo].[HT_Register] (  [id] int,  [Reg_no] varchar(250),  [Reg_Date] datetime,  [Reg_Room] varchar(250),  [Reg_Name] varchar(250),  [Reg_Address] varchar(500),  [Reg_Doing] varchar(250),  [Reg_Nation] varchar(
-- Table: dbo.HT_Room_SMSCREATE TABLE [dbo].[HT_Room_SMS] (  [SMS_ID] int IDENTITY NOT NULL,  [SMS_Room] varchar(50),  [SMS_Details] text,  [SMS_By] varchar(250),  [SMS_Readed] varchar(50));
-- Table: dbo.HT_Room_StatusCREATE TABLE [dbo].[HT_Room_Status] (  [id] int,  [room_no] varchar(50),  [room_date] datetime,  [room_status] varchar(50),  [room_Details] varchar(500),  [room_Book_No] varchar(50),  [room_CheckIn_No] varchar(50),  [ro
-- Table: dbo.HT_RoomsCREATE TABLE [dbo].[HT_Rooms] (  [id] int,  [Room_no] varchar(50),  [Room_Type] varchar(50),  [Room_Details] varchar(500),  [Room_PriceA] float,  [Room_PriceB] float,  [Room_PriceC] float,  [Room_Clean] varchar(50) NOT NULL D
-- Table: dbo.HT_Rooms_CancelCREATE TABLE [dbo].[HT_Rooms_Cancel] (  [id] int,  [room_no] varchar(50),  [cin_no] varchar(50),  [cancel_date] datetime,  [cancel_by] varchar(50),  [cancel_note] text);
-- Table: dbo.HT_Rooms_PriceCREATE TABLE [dbo].[HT_Rooms_Price] (  [id] int IDENTITY NOT NULL,  [Room_Type] varchar(50),  [Room_CustType] varchar(50),  [Room_Price] float,  [Room_Price_H] float,  [Room_Price_M] float);
-- Table: dbo.HT_Rooms_RepairCREATE TABLE [dbo].[HT_Rooms_Repair] (  [id] int IDENTITY NOT NULL,  [room_no] varchar(50),  [Repair_date] datetime,  [Repair_by] varchar(250),  [Repair_note] text);
-- Table: dbo.HT_Round_BillCREATE TABLE [dbo].[HT_Round_Bill] (  [id] int NOT NULL,  [round_no] int,  [round_price] float,  [round_by] varchar(150),  [round_start] datetime,  [round_end] datetime);
-- Table: dbo.HT_SET_CusTypeCREATE TABLE [dbo].[HT_SET_CusType] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(50),  [deposit] float NOT NULL DEFAULT ((0)));
-- Table: dbo.HT_SET_CusType_MainCREATE TABLE [dbo].[HT_SET_CusType_Main] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(50));
-- Table: dbo.HT_SET_ProductTypeCREATE TABLE [dbo].[HT_SET_ProductType] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(50));
-- Table: dbo.HT_SET_RoomTypeCREATE TABLE [dbo].[HT_SET_RoomType] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(50),  [Room_PriceA] float,  [Room_PriceB] float,  [Room_PriceC] float);
-- Table: dbo.HT_SET_SaleCREATE TABLE [dbo].[HT_SET_Sale] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(150),  [tel] varchar(50),  [address] varchar(400),  [other] varchar(500));
-- Table: dbo.TB_FOLIOCREATE TABLE [dbo].[TB_FOLIO] (  [id] int,  [NO] varchar(20),  [CIN_NAME1] varchar(255),  [CIN_NAME2] varchar(255),  [CIN_NAME3] varchar(255),  [F_ROOM] varchar(50),  [F_NAME] varchar(250),  [F_IN] varchar(50),  [F_OUT] varc
-- Table: dbo.TB_MRP_EMPLOYEECREATE TABLE [dbo].[TB_MRP_EMPLOYEE] (  [ID] int IDENTITY NOT NULL,  [Emp_Username] varchar(50),  [Emp_Password] varchar(50),  [Emp_Name] varchar(50),  [Emp_Level] varchar(50),  [Emp_Vat] varchar(50));
-- Table: dbo.TB_MRP_PermissionCREATE TABLE [dbo].[TB_MRP_Permission] (  [Level_Name] varchar(50),  [Level_Command] varchar(50));
-- Table: dbo.TB_MRP_Permission_nameCREATE TABLE [dbo].[TB_MRP_Permission_name] (  [Permission_name] varchar(50));
-- Table: dbo.TB_Pay_HistoryCREATE TABLE [dbo].[TB_Pay_History] (  [id] int,  [Pay_Date] float,  [Pay_Bill] varchar(255),  [Pay_Cust] varchar(500),  [Pay_Type] varchar(50),  [Pay_Total] float,  [Pay_Note] varchar(500),  [Pay_Program] float,  [Pay
-- Table: dbo.Tb_Save_ImageCREATE TABLE [dbo].[Tb_Save_Image] (  [id] int IDENTITY NOT NULL,  [cin_no] varchar(50),  [ttype] varchar(250),  [pic] varbinary,  [cust_no] varchar(50),  [tmp_no] varchar(50),  [pic_date] datetime);
-- Table: dbo.TB_SET_BranchCREATE TABLE [dbo].[TB_SET_Branch] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(100));
-- Table: dbo.TB_SET_MyType2CREATE TABLE [dbo].[TB_SET_MyType2] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(100));
-- Table: dbo.TB_SET_MyType2_2CREATE TABLE [dbo].[TB_SET_MyType2_2] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(100));
-- Table: dbo.TB_SET_MyType3CREATE TABLE [dbo].[TB_SET_MyType3] (  [id] int IDENTITY NOT NULL,  [id_full] varchar(50),  [name] varchar(100));
-- Table: dbo.TB_SETTINGSCREATE TABLE [dbo].[TB_SETTINGS] (  [Company_Name] varchar(500),  [Company_Address] varchar(500),  [Company_Tel] varchar(100),  [Company_Fax] varchar(100),  [Company_Image] varbinary,  [Company_Tax] varchar(50),  [CHK_IN_Be
-- Table: dbo.Tb_VersionCREATE TABLE [dbo].[Tb_Version] (  [V_NO] varchar(50));
